# Generated by Django 6.0.4 on 2026-04-17 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_appid', models.PositiveIntegerField(unique=True)),
                ('engine', models.CharField(blank=True, max_length=32)),
                ('api_target', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('developer', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=32)),
                ('url_header', models.URLField(blank=True)),
                ('url_capsule', models.URLField(blank=True)),
                ('url_background', models.URLField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')])),
                ('notes', models.TextField(blank=True)),
                ('config_file', models.FileField(blank=True, upload_to='presets/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='configvault.game')),
            ],
            options={
                'unique_together': {('game', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
                ('impact', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=32)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='configvault.preset')),
            ],
        ),
    ]
