# Generated by Django 6.0.4 on 2026-04-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configvault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='deck_verification',
            field=models.CharField(blank=True, choices=[(0, 'Unknown'), (1, 'Verified'), (2, 'Playable'), (3, 'Unverified'), (4, 'Unplayable')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Steam Deck')]),
        ),
    ]
