# Generated by Django 6.0.4 on 2026-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configvault', '0002_preset_deck_verification_alter_preset_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='deck_verification',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Verified', 'Verified'), ('Playable', 'Playable'), ('Unverified', 'Unverified'), ('Unplayable', 'Unplayable')], default='Unknown', max_length=32),
        ),
    ]
