# Generated by Django 6.0.4 on 2026-04-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configvault', '0003_alter_preset_deck_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='api_target',
            field=models.CharField(blank=True, choices=[('DX7', 'DirectX 7'), ('DX9', 'DirectX 9'), ('GL', 'OpenGL'), ('VK', 'Vulkan'), ('MTL', 'Metal'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _migrate_engine_strings_to_engine_table(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='game',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='configvault.engine'),
        ),
    ]


def _migrate_engine_strings_to_engine_table(apps, schema_editor):
    """Create Engine rows for existing free-text engine values and
    update the game rows to reference the new engine IDs.

    This prepares the DB so the following AlterField to a ForeignKey
    succeeds without referential integrity errors.
    """
    Engine = apps.get_model('configvault', 'Engine')
    Game = apps.get_model('configvault', 'Game')
    # Use the historical ORM models to discover existing free-text engine
    # values, create Engine rows, and update the Game records to point to
    # the newly-created Engine objects.
    mapping = {}
    # Collect distinct engine strings
    distinct_engines = (
        Game.objects.values_list('engine', flat=True)
        .distinct()
        .exclude(engine__isnull=True)
        .exclude(engine__exact='')
    )
    for engine_name in distinct_engines:
        # Create Engine record for this text value (empty version)
        engine_obj = Engine.objects.create(name=engine_name, version='')
        mapping[engine_name] = engine_obj.id

    # Update Game records to reference the new Engine IDs
    for name, eid in mapping.items():
        Game.objects.filter(engine=name).update(engine=eid)
