# Generated by Django 6.0.4 on 2026-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configvault', '0004_alter_game_api_target_engine_alter_game_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='api_target',
            field=models.CharField(blank=True, choices=[('DX7', 'DirectX 7'), ('DX8', 'DirectX 8'), ('DX9', 'DirectX 9'), ('DX10', 'DirectX 10'), ('DX11', 'DirectX 11'), ('DX12', 'DirectX 12'), ('GL', 'OpenGL'), ('GLES', 'OpenGL ES'), ('VK', 'Vulkan'), ('MTL', 'Metal'), ('WEBGL', 'WebGL'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
